---
roles:
  - blobstore:   10.138.68.2
  - nats:        10.138.68.2
  - postgresql:  10.138.68.2
  - redis:       10.138.68.2
  - director:    10.138.68.2
user: vcap
paths:
  repo_cache: /var/vcap/deploy/repos
  cookbooks: /var/vcap/deploy/cookbooks
  chef: /var/vcap/deploy/chef
