---
roles:
  director:   10.138.68.2
  postgresql: 10.138.68.2
  redis:      10.138.68.2
  nats:       10.138.68.2
  blobstore:  10.138.68.2
deploy_order:
  - blobstore
  - nats
  - postgres
  - redis
  - director
user: vcap
paths:
  repo_cache: /var/vcap/deploy/repos
  cookbooks: /var/vcap/deploy/cookbooks
  chef: /var/vcap/deploy/chef
