---
roles:
  director:   172.30.252.115
  postgresql: 172.30.252.115
  redis:      172.30.252.115
  nats:       172.30.40.12
  blobstore:  172.30.40.12
deploy_order:
  - blobstore
  - nats
  - postgres
  - redis
  - director
user: vcap
gateway: las-jump
paths:
  repo_cache: /var/vcap/deploy/repos
  cookbooks: /var/vcap/deploy/cookbooks
  chef: /var/vcap/deploy/chef
