---
roles:
  - nats:       172.30.40.12
  - blobstore:  172.30.40.12
  - redis:      172.30.252.115
  - postgresql: 172.30.252.115
  - director:   172.30.252.115
user: vcap
gateway: las-jump
paths:
  repo_cache: /var/vcap/deploy/repos
  cookbooks: /var/vcap/deploy/cookbooks
  chef: /var/vcap/deploy/chef
