---
roles:
  - blobstore:   172.31.113.128
  - nats:        172.31.113.128
  - postgresql:  172.31.113.128
  - redis:       172.31.113.128
  - director:    172.31.113.128
user: vcap
password: vcap
gateway:
paths:
  repo_cache: /var/vcap/deploy/repos
  cookbooks: /var/vcap/deploy/cookbooks
  chef: /var/vcap/deploy/chef
