---
roles:
  director:   172.31.113.145
  postgresql: 172.31.113.145
  redis:      172.31.113.145
  nats:       172.31.113.145
  blobstore:  172.31.113.145
user: vcap
paths:
  repo_cache: /var/vcap/deploy/repos
  cookbooks: /var/vcap/deploy/cookbooks
  chef: /var/vcap/deploy/chef
