---
port: 8080
logging:
  level: DEBUG
redis:
  host: 127.0.0.1
  password:
dir: /tmp/boshdir
blobstore:
  plugin: simple
  properties:
    endpoint: http://127.0.0.1
    user: admin
    password:
cloud:
  plugin: vsphere
  properties:
    agent:
      blobstore:
        plugin: simple
        properties:
          endpoint: http://127.0.0.1
          user: agent
          password:
      server:
        host: 127.0.0.1
        password:
    vcenters:
      - host: localhost:10443
        user: vmware
        password:
        tunnel: las-jump
        datacenters:
          - name: LAS01
            vm_folder: BOSH_VMs
            template_folder: BOSH_Templates
            clusters:
              - Cluster01
              - Cluster02
              - Cluster03
              - Cluster04
              - Cluster05
              - Cluster06
