---
roles:
  - blobstore:   172.31.113.152
  - nats:        172.31.113.152
  - postgresql:  172.31.113.152
  - redis:       172.31.113.152
  - director:    172.31.113.152
user: vcap
paths:
  repo_cache: /var/vcap/deploy/repos
  cookbooks: /var/vcap/deploy/cookbooks
  chef: /var/vcap/deploy/chef
